### ISSUE TITLE
v1.2.2 (Tweego 2) flagged by virus scanner

### ISSUE THREAD

**Issue by VeliV** [ChapelR/tweego-installer#5]
Looks like the the installer is flagged by https://www.virustotal.com/gui/file/e8a1861cbd61faad6577452b6370bfc3ef0976d18d2c84a1ea2fb98dc1c5b518/detection

Ran it through some other online scanners as well, but they didn't find anything. Probably a false positive?

**Comment by ChapelR** [comment]
Yeah it's likely a false positive, it's just a compiled inno setup script, the Tweego executable, and a few JavaScript files. I should be able to submit the file for manual review.

**Comment by VeliV** [comment]
Wow, didn't expect such a fast response :D Thanks!

**Comment by ChapelR** [comment]
Gonna go ahead and close this.
